name: carnd-advdl-odlab
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6.1
    - pip
    - pip:
        - moviepy
        - tensorflow==1.12.0
        - numpy
        - matplotlib
        - jupyter
        - pillow
        - scipy
        - ffmpeg
        - imageio==2.1.2
